# https://docs.travis-ci.com/user/environment-variables/
language: csharp
dotnet: 1.0.0-preview2-1-003177
services:
  - docker

script:
  - export DOCKER_TAG="1.0.$TRAVIS_BUILD_NUMBER"
  - echo "Using $DOCKER_TAG for the Docker tag"
  - dotnet restore
  - dotnet publish src/Letmein.Web -c Release
  - cd src/Letmein.Web
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker build -t "anotherchris/letmein:$DOCKER_TAG" .
  - docker push "anotherchris/letmein:$DOCKER_TAG"