# https://docs.travis-ci.com/user/environment-variables/
language: csharp
dotnet: 1.0.0-preview2-1-003177

branches:
  only:
  - master

services:
  - docker
  - postgresql

addons:
  postgresql: "9.5"

# Symbolic link is a fix for Ubuntu using "nodejs" not "node"
install:
  - sudo ln -s /usr/bin/nodejs /usr/bin/node
  - cd src/Letmein.Web/wwwroot
  - npm install
  - cd ../../../

before_script:
  - psql -c 'create database letmein;' -U postgres

script:
  - cd src/Letmein.Web/wwwroot
  - ./node_modules/.bin/gulp
  - cd ../../../
  - export POSTGRES_CONNECTIONSTRING="host=localhost;database=letmein;username=postgres;password="
  - chmod 777 ./travis/replace-version.sh
  - chmod 777 ./travis/clean-wwwroot.sh
  - ./travis/replace-version.sh
  - ./travis/clean-wwwroot.sh
  - export DOCKER_TAG="1.0.$TRAVIS_BUILD_NUMBER"
  - echo "Using $DOCKER_TAG for the Docker tag"
  - dotnet restore
  - cd src/Letmein.Tests/
  - dotnet test
  - cd ../../
  - dotnet publish src/Letmein.Web -c Release
  - cd src/Letmein.Web
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker build -t "anotherchris/letmein:latest" -t "anotherchris/letmein:$DOCKER_TAG" .
  - docker push "anotherchris/letmein:$DOCKER_TAG"
  - docker push "anotherchris/letmein:latest"
