# https://docs.travis-ci.com/user/environment-variables/
language: csharp
dotnet: 1.0.0-preview2-1-003177

branches:
  only:
  - master
  - deletebutton

services:
  - docker
  - postgresql

addons:
  postgresql: "9.5"

install:
  - npm install babel-cli
  - npm install uglify-js
  - npm install babel-preset-env
  - npm install gulp
  - npm install gulp-cli
  - npm install gulp-babel
  - npm install gulp-uglify
  - npm install gulp-concat
  - npm install gulp-rename

before_script:
  - psql -c 'create database letmein;' -U postgres

script:
  - cd src/Letmein.Web/wwwroot
  - gulp
  - cd ../../../
  - export POSTGRES_CONNECTIONSTRING="host=localhost;database=letmein;username=postgres;password="
  - chmod 777 ./travis/replace-version.sh
  - chmod 777 ./travis/prepare-wwwroot.sh
  - ./travis/replace-version.sh
  - ./travis/prepare-wwwroot.sh
  - export DOCKER_TAG="1.0.$TRAVIS_BUILD_NUMBER"
  - echo "Using $DOCKER_TAG for the Docker tag"
  - dotnet restore
  - cd src/Letmein.Tests/
  - dotnet test
  - cd ../../
  - dotnet publish src/Letmein.Web -c Release
  - cd src/Letmein.Web
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker build -t "anotherchris/letmein:latest" -t "anotherchris/letmein:$DOCKER_TAG" .
  - echo docker push "anotherchris/letmein:$DOCKER_TAG"
  - echo docker push "anotherchris/letmein:latest"
