language: csharp
dotnet: 1.0.0-preview2-1-003177
services:
  - docker

script:
  - export DOCKER_TAG="1.0.$TRAVIS_BUILD_NUMBER"
  - dotnet restore
  - dotnet publish src/Letmein.Web -c Release
  - dotnet publish src/Letmein.Cleanup -c Release
  - cd src/Letmein.Web
  - docker build -t anotherchris/letmein:$DOCKER_TAG
